### ISSUE TITLE
training Error: could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by n2ballroy** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#21]
Your tutorial is excellant and I was able to modify it to work completely with custom training without a gpu.  Now I have a new computer with GPU and I am having the error shown in the subject and shown in the excerpt at the bottom.  I have upgraded the cuda to 9.0 and the CuDNN to 7.1.2.

I found this link regarding the error
https://github.com/tensorflow/tensorflow/issues/6698
strickon comments

which details how to fix this issue which is due to an apparent gpu memory issue.  This is supposed to keep tensorflow from allocating too much gpu memory by adding the following...

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config, ...)

My problem is that I don't know how to implement this change within the framework of your github tutorial.

**Need help.**  Thanks in advance

excerpt of output from train.py

2018-04-09 10:19:22.033369: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1344] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB
2018-04-09 10:19:22.033539: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1423] Adding visible gpu devices: 0
2018-04-09 10:20:33.854527: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-09 10:20:33.854633: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:917]      0
2018-04-09 10:20:33.855370: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:930] 0:   N
2018-04-09 10:20:33.856016: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6403 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from training/model.ckpt-0
INFO:tensorflow:Restoring parameters from training/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path training/model.ckpt
INFO:tensorflow:Saving checkpoint to path training/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
2018-04-09 10:20:48.489995: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:403] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2018-04-09 10:20:48.494500: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:407] error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2018-04-09 10:20:48.510150: F T:\src\github\tensorflow\tensorflow\core\kernels\conv_ops.cc:712] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)

**Comment by alhparsa** [comment]
Try this: 
go to trainer.py and find the following line:
`session_config = tf.ConfigProto(allow_soft_placement=True,
                                    log_device_placement=False)`
replace it with:
`
gpu_options = tf.GPUOptions(allow_growth=True)
session_config = tf.ConfigProto(allow_soft_placement=True,
                                    log_device_placement=False, gpu_options=gpu_options)
`

see if that works. otherwise, make sure your CUDDN driver is installed properly and matches your tensorflow version.

**Comment by n2ballroy** [comment]
Thanks for the very well explained help.  It turns out the error was
cleared up by dropping back from CudNN 7.1 to 7.0.  According to NVidia 7.1
should have worked.

I started at Tensor 1.7, cudNN 8.1, cuda 9.1.  This had the error.

I then went to  Tensor 1.5, cudNN 7.1, cuda 8.0.  This had the error

I was successful when I went to Tensorflow 1.5, cudNN 7.0, cuda 8.0.

**Comment by n2ballroy** [comment]
Issue closed.  Just keep trying cuda versions until the issue went away.

This combo worked
Tensorflow 1.5, cudNN 7.0, cuda 8.0

**Comment by srama2512** [comment]
> Issue closed. Just keep trying cuda versions until the issue went away.
> 
> This combo worked
> Tensorflow 1.5, cudNN 7.0, cuda 8.0

Thank you! I had the same issues and I was able to resolve it by downgrading to tensorflow 1.5.0 and using cuda 9.0, cudnn 7.0.5. Looks like it might be an issue with tensorflow itself rather than the cuda version. Some details below for reference:

```
pip install tensorflow-gpu==1.5.0
export CUDNN_PATH=<path to libcudnn.so>
export CUDNN_INCLUDE_DIR=<path to cudnn/cuda/include>
export CUDNN_LIBRARY=<path to cudnn-v7.0.5/cuda/lib64>
export LD_LIBRARY_PATH=<path to cudnn-v7.0.5/cuda/lib64>
```

**Comment by Samitha156** [comment]
@mugenop @srama2512 Hello , Please tell me I have installed cudnn 7.0 previously and by mistake upgraded it . now it is cudnn 7.3.1 . I wanna downgrade back to 7.0  . How can I do it?

**Comment by eXisting** [comment]
For me, it was about TF and cudnn version incompatibility (was 1.12 and 7.3 and became 1.8 and 6.0)

I am using Anaconda env, so downgrading is very easy from GUI. Just donwgrade you TF version and cudnn version to those you are able to run with. Hope it will help someone.
