### ISSUE TITLE
Could not find 'cudart64_100.dll' during Import tensorflow - CUDA 10.1 Incompatible with Tensorflow

### ISSUE THREAD

**Issue by AeroWRX** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#340]
> ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive

The tensorflow model repository has a self_check.py file that will fail every time if we download and install the latest CUDA/cuDNN 10.1 because the DLL files are titled "cudart64_101.dll" and it won't find the "...64_100.dll" ever.

**Comment by mmortazavi** [comment]
I have had a very similar issue with  dll missing. I suggest you double check you exactly use CUDA 10.0 not CUDA 10.1 and also the corresponding CUDNN 10.0! This solved my dll missing errors with Tensorflow 1.14.0.

**Comment by Petros626** [comment]
@mmortazavi Hey I use TF 1.15 and CUDA 10.0 but it says, that the dll is still not there..

**Comment by mmortazavi** [comment]
@Petros626 Unfortunately I cannot comment, it has been over 2 years. I also no longer use the repo. I kind of leaned towards other object detection methods like YoloV5 (https://github.com/ultralytics/yolov5), check them out. In my use cases, it outperform TF models.
